using HRManagementSoftware.PayrollAdjustments;
using Xunit;
using HRManagementSoftware.EntityFrameworkCore;

namespace HRManagementSoftware.PayrollAdjustments;

public class EfCorePayrollAdjustmentsAppServiceTests : PayrollAdjustmentsAppServiceTests<HRManagementSoftwareEntityFrameworkCoreTestModule>
{
}