using Volo.Abp.Identity;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace HRManagementSoftware.HRManagers
{
    public class HRManager : HRManagerBase
    {
        //<suite-custom-code-autogenerated>
        protected HRManager()
        {

        }

        public HRManager(Guid id, Guid? identityUserId, string hRNumber, string department)
            : base(id, identityUserId, hRNumber, department)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}