using HRManagementSoftware.Shared;
using HRManagementSoftware.Employees;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HRManagementSoftware.Permissions;
using HRManagementSoftware.LeaveRequests;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using HRManagementSoftware.Shared;

namespace HRManagementSoftware.LeaveRequests
{
    public class LeaveRequestsAppService : LeaveRequestsAppServiceBase, ILeaveRequestsAppService
    {
        //<suite-custom-code-autogenerated>
        public LeaveRequestsAppService(ILeaveRequestRepository leaveRequestRepository, LeaveRequestManager leaveRequestManager, IDistributedCache<LeaveRequestDownloadTokenCacheItem, string> downloadTokenCache, IRepository<HRManagementSoftware.Employees.Employee, Guid> employeeRepository)
            : base(leaveRequestRepository, leaveRequestManager, downloadTokenCache, employeeRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}