using Xunit;

namespace HRManagementSoftware.EntityFrameworkCore;

[CollectionDefinition(HRManagementSoftwareTestConsts.CollectionDefinitionName)]
public class HRManagementSoftwareEntityFrameworkCoreCollection : ICollectionFixture<HRManagementSoftwareEntityFrameworkCoreFixture>
{

}
