using HRManagementSoftware.EntityFrameworkCore;
using Xunit;

namespace HRManagementSoftware.EntityFrameworkCore;

public class HRManagementSoftwareEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<HRManagementSoftwareEntityFrameworkCoreFixture>
{

}
