using HRManagementSoftware;
using HRManagementSoftware.Employees;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace HRManagementSoftware.LeaveRequests
{
    public class LeaveRequest : LeaveRequestBase
    {
        //<suite-custom-code-autogenerated>
        protected LeaveRequest()
        {

        }

        public LeaveRequest(Guid id, Guid? employeeId, LeaveType leaveType, LeaveStatus leaveStatus, DateTime startDate, DateTime endDate, string reason, DateTime requestDate)
            : base(id, employeeId, leaveType, leaveStatus, startDate, endDate, reason, requestDate)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}