using HRManagementSoftware;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace HRManagementSoftware.LeaveRequests
{
    public class LeaveRequestManager : LeaveRequestManagerBase
    {
        //<suite-custom-code-autogenerated>
        public LeaveRequestManager(ILeaveRequestRepository leaveRequestRepository)
            : base(leaveRequestRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}