using Volo.Abp.Identity;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace HRManagementSoftware.Employees
{
    public class Employee : EmployeeBase
    {
        //<suite-custom-code-autogenerated>
        protected Employee()
        {

        }

        public Employee(Guid id, Guid? identityUserId, string employeeNumber, string jobTitle, DateTime dateOfJoining, decimal paidLeaveBalance, decimal sickLeaveBalance, decimal unpaidLeaveBalance, decimal baseSalary)
            : base(id, identityUserId, employeeNumber, jobTitle, dateOfJoining, paidLeaveBalance, sickLeaveBalance, unpaidLeaveBalance, baseSalary)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}