using HRManagementSoftware.Shared;
using Volo.Abp.Identity;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HRManagementSoftware.Permissions;
using HRManagementSoftware.HRManagers;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using HRManagementSoftware.Shared;

namespace HRManagementSoftware.HRManagers
{
    public class HRManagersAppService : HRManagersAppServiceBase, IHRManagersAppService
    {
        //<suite-custom-code-autogenerated>
        public HRManagersAppService(IHRManagerRepository hRManagerRepository, HRManagerManager hRManagerManager, IDistributedCache<HRManagerDownloadTokenCacheItem, string> downloadTokenCache, IRepository<Volo.Abp.Identity.IdentityUser, Guid> identityUserRepository)
            : base(hRManagerRepository, hRManagerManager, downloadTokenCache, identityUserRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}