using HRManagementSoftware.Shared;
using Volo.Abp.Identity;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HRManagementSoftware.Permissions;
using HRManagementSoftware.HRManagers;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;

namespace HRManagementSoftware.HRManagers
{
    public class HRManagersAppService : HRManagersAppServiceBase, IHRManagersAppService
    {
        //<suite-custom-code-autogenerated>
        public HRManagersAppService(IHRManagerRepository hRManagerRepository, HRManagerManager hRManagerManager, IDistributedCache<HRManagerDownloadTokenCacheItem, string> downloadTokenCache, IRepository<Volo.Abp.Identity.IdentityUser, Guid> identityUserRepository)
            : base(hRManagerRepository, hRManagerManager, downloadTokenCache, identityUserRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
        public async Task<HRManagerDto> GetNewHRNumberAsync()
        {
            // Using CurrentUser as per reference
            var currentUserId = CurrentUser.Id;
            if (!currentUserId.HasValue)
            {
                throw new AbpAuthorizationException("User not authenticated");
            }

            // Get HR for the current user
            var queryable = await _hRManagerRepository.GetQueryableAsync();
            var hrManager = await AsyncExecuter.FirstOrDefaultAsync(
                queryable.Where(e => e.IdentityUserId == currentUserId.Value)
            );

            if (hrManager == null)
            {
                // No HR found for the user
                return new HRManagerDto(); // Return empty DTO
            }

            // Return existing HR details
            return ObjectMapper.Map<HRManager, HRManagerDto>(hrManager);
        }
    }
}