using HRManagementSoftware.Shared;
using Volo.Abp.Identity;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HRManagementSoftware.Permissions;
using HRManagementSoftware.HRManagers;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;

namespace HRManagementSoftware.HRManagers
{
    public class HRManagersAppService : HRManagersAppServiceBase, IHRManagersAppService
    {
        //<suite-custom-code-autogenerated>
        public HRManagersAppService(IHRManagerRepository hRManagerRepository, HRManagerManager hRManagerManager, IDistributedCache<HRManagerDownloadTokenCacheItem, string> downloadTokenCache, IRepository<Volo.Abp.Identity.IdentityUser, Guid> identityUserRepository)
            : base(hRManagerRepository, hRManagerManager, downloadTokenCache, identityUserRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
        public async Task<HRManagerDto> GetNewHRNumberAsync()
        {
            // Using CurrentUser as per reference
            var currentUserId = CurrentUser.Id;

            // Generate new HR number
            var queryable = await _hRManagerRepository.GetQueryableAsync();
            var maxHRNumber = await AsyncExecuter.FirstOrDefaultAsync(
                queryable.OrderByDescending(e => e.HRNumber).Select(e => e.HRNumber)
            );

            string newHRNumber;
            if (string.IsNullOrEmpty(maxHRNumber))
            {
                newHRNumber = "001";
            }
            else if (int.TryParse(maxHRNumber, out int currentNumber))
            {
                newHRNumber = (currentNumber + 1).ToString("D3");
            }
            else
            {
                newHRNumber = maxHRNumber + "1";
            }

            // Return HRManagerDto with generated number and default data
            return new HRManagerDto
            {
                Id = Guid.NewGuid(), // Temporary ID
                IdentityUserId = currentUserId,
                HRNumber = newHRNumber,
                Department = "New Department"
            };
        }
    }
}