using HRManagementSoftware.Shared;
using HRManagementSoftware.Employees;
using HRManagementSoftware.LeaveRequests;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HRManagementSoftware.Permissions;
using HRManagementSoftware.PayrollAdjustments;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using HRManagementSoftware.Shared;

namespace HRManagementSoftware.PayrollAdjustments
{
    public class PayrollAdjustmentsAppService : PayrollAdjustmentsAppServiceBase, IPayrollAdjustmentsAppService
    {
        //<suite-custom-code-autogenerated>
        public PayrollAdjustmentsAppService(IPayrollAdjustmentRepository payrollAdjustmentRepository, PayrollAdjustmentManager payrollAdjustmentManager, IDistributedCache<PayrollAdjustmentDownloadTokenCacheItem, string> downloadTokenCache, IRepository<HRManagementSoftware.LeaveRequests.LeaveRequest, Guid> leaveRequestRepository, IRepository<HRManagementSoftware.Employees.Employee, Guid> employeeRepository)
            : base(payrollAdjustmentRepository, payrollAdjustmentManager, downloadTokenCache, leaveRequestRepository, employeeRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}