using HRManagementSoftware.Shared;
using Volo.Abp.Identity;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HRManagementSoftware.Permissions;
using HRManagementSoftware.Employees;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;

namespace HRManagementSoftware.Employees
{
    public class EmployeesAppService : EmployeesAppServiceBase, IEmployeesAppService
    {
        //<suite-custom-code-autogenerated>
        public EmployeesAppService(IEmployeeRepository employeeRepository, EmployeeManager employeeManager, IDistributedCache<EmployeeDownloadTokenCacheItem, string> downloadTokenCache, IRepository<Volo.Abp.Identity.IdentityUser, Guid> identityUserRepository)
            : base(employeeRepository, employeeManager, downloadTokenCache, identityUserRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
        public async Task<EmployeeDto> GetNewEmployeeNumberAsync()
        {
            // Using CurrentUser as per reference
            var currentUserId = CurrentUser.Id;
            if (!currentUserId.HasValue)
            {
                throw new AbpAuthorizationException("User not authenticated");
            }

            // Get employee for the current user
            var queryable = await _employeeRepository.GetQueryableAsync();
            var employee = await AsyncExecuter.FirstOrDefaultAsync(
                queryable.Where(e => e.IdentityUserId == currentUserId.Value)
            );

            if (employee == null)
            {
                // No employee found for the user
                return new EmployeeDto(); // Return empty DTO
            }

            // Return existing employee details
            return ObjectMapper.Map<Employee, EmployeeDto>(employee);
        }
    }
}


