using HRManagementSoftware.Shared;
using Volo.Abp.Identity;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using HRManagementSoftware.Permissions;
using HRManagementSoftware.Employees;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;

namespace HRManagementSoftware.Employees
{
    public class EmployeesAppService : EmployeesAppServiceBase, IEmployeesAppService
    {
        //<suite-custom-code-autogenerated>
        public EmployeesAppService(IEmployeeRepository employeeRepository, EmployeeManager employeeManager, IDistributedCache<EmployeeDownloadTokenCacheItem, string> downloadTokenCache, IRepository<Volo.Abp.Identity.IdentityUser, Guid> identityUserRepository)
            : base(employeeRepository, employeeManager, downloadTokenCache, identityUserRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
        public async Task<EmployeeDto> GetNewEmployeeNumberAsync()
        {
            // Using CurrentUser as per reference
            var currentUserId = CurrentUser.Id;

            // Generate new employee number
            var queryable = await _employeeRepository.GetQueryableAsync();
            var maxEmployeeNumber = await AsyncExecuter.FirstOrDefaultAsync(
                queryable.OrderByDescending(e => e.EmployeeNumber).Select(e => e.EmployeeNumber)
            );

            string newEmployeeNumber;
            if (string.IsNullOrEmpty(maxEmployeeNumber))
            {
                newEmployeeNumber = "001";
            }
            else if (int.TryParse(maxEmployeeNumber, out int currentNumber))
            {
                newEmployeeNumber = (currentNumber + 1).ToString("D3");
            }
            else
            {
                newEmployeeNumber = maxEmployeeNumber + "1";
            }

            // Return EmployeeDto with generated number and default data
            return new EmployeeDto
            {
                Id = Guid.NewGuid(), // Temporary ID
                IdentityUserId = currentUserId,
                EmployeeNumber = newEmployeeNumber,
                JobTitle = "New Employee",
                DateOfJoining = DateTime.Now,
                PaidLeaveBalance = 0,
                SickLeaveBalance = 0,
                UnpaidLeaveBalance = 0,
                BaseSalary = 0
            };
        }
    }
}


