using HRManagementSoftware;
using HRManagementSoftware.LeaveRequests;
using HRManagementSoftware.Employees;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace HRManagementSoftware.PayrollAdjustments
{
    public class PayrollAdjustment : PayrollAdjustmentBase
    {
        //<suite-custom-code-autogenerated>
        protected PayrollAdjustment()
        {

        }

        public PayrollAdjustment(Guid id, Guid? leaveRequestId, Guid? employeeId, int month, int year, PayrollRecordStatus status, decimal netpay)
            : base(id, leaveRequestId, employeeId, month, year, status, netpay)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}