using HRManagementSoftware;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace HRManagementSoftware.PayrollAdjustments
{
    public class PayrollAdjustmentManager : PayrollAdjustmentManagerBase
    {
        //<suite-custom-code-autogenerated>
        public PayrollAdjustmentManager(IPayrollAdjustmentRepository payrollAdjustmentRepository)
            : base(payrollAdjustmentRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}